
<table width="100%" border="0" cellspacing="0" cellpadding="0" id="menu_vendedor">
    <tr>
    <td>
    <ul>
        <li><a href="restrito_acompanhar_solicitacao_comprador.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image15','','imagens/painel_empresa/btn_acompanhar_solicitacao2.jpg',1)"><img src="imagens/painel_empresa/btn_acompanhar_solicitacao1.jpg" name="Image15" width="230" height="28" border="0" id="Image15" /></a></li>
        <li><a href="restrito_vendedor_minhas_solicitacoes.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image40','','imagens/painel_empresa/btn_solicitacao_ganha_h.jpg',1)"><img src="imagens/painel_empresa/btn_solicitacao_ganha.jpg" name="Image40" width="230" height="28" border="0"></a></li>
        <li><a href="restrito_vendedor_avaliacao.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image20','','imagens/painel_empresa/btn_avaliacao2.jpg',1)"><img src="imagens/painel_empresa/btn_avaliacao1.jpg" name="Image20" width="230" height="28" border="0" id="Image20" /></a></li>
            <li><a href="restrito_altera_categ_empresa.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image12','','imagens/painel_empresa/btn_alterar_categorias2.jpg',1)"><img src="imagens/painel_empresa/btn_alterar_categorias1.jpg" name="Image12" width="230" height="28" border="0"></a></li>
        <li><a href="restrito_vendedor_atualizar_limite.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image21','','imagens/painel_empresa/btn_limite_plano2.jpg',1)"><img src="imagens/painel_empresa/btn_limite_plano1.jpg" name="Image21" width="230" height="28" border="0" id="Image21" /></a></li>
        <li><a href="lista_planos.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image19','','imagens/painel_empresa/btn_alterar_plano2.jpg',1)"><img src="imagens/painel_empresa/btn_alterar_plano1.jpg" name="Image19" width="230" height="28" border="0" id="Image19" /></a></li>
        <li><a href="restrito_vendedor_atualizar_descricao.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image16','','imagens/painel_empresa/btn_alterar_descricao2.jpg',1)"><img src="imagens/painel_empresa/btn_alterar_descricao1.jpg" name="Image16" width="230" height="28" border="0" id="Image16" /></a></li>
        <li><a href="restrito_vendedor_atualizar_logo.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image17','','imagens/painel_empresa/btn_atualizar_logotipo2.jpg',1)"><img src="imagens/painel_empresa/btn_atualizar_logotipo1.jpg" name="Image17" width="230" height="28" border="0" id="Image17" /></a></li>
        <li><a href="restrito_vendedor_atualizar_fotos.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image18','','imagens/painel_empresa/btn_atualizar_fotos2.jpg',1)"><img src="imagens/painel_empresa/btn_atualizar_fotos1.jpg" name="Image18" width="230" height="28" border="0" id="Image18" /></a></li>
        <li><a href="restrito_altera_dados_empresa.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image9','','imagens/painel_empresa/btn_alterar_dados2.jpg',1)"><img src="imagens/painel_empresa/btn_alterar_dados1.jpg" name="Image9" width="230" height="28" border="0"></a></li>
        <li><a href="restrito_altera_senha_empresa.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image10','','imagens/painel_empresa/btn_alterar_senha2.jpg',1)"><img src="imagens/painel_empresa/btn_alterar_senha1.jpg" name="Image10" width="230" height="28" border="0"></a></li>
<!--    <li><a href="detalhes_solicitacoes.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image11','','imagens/painel_empresa/btn_minha_solicitacao2.jpg',1)"><img src="imagens/painel_empresa/btn_minha_solicitacao1.jpg" name="Image11" width="230" height="28" border="0"></a></li>
        <li><a href="nova_solicitacao.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image12','','imagens/painel_empresa/btn_nova_solicitacao2.jpg',1)"><img src="imagens/painel_empresa/btn_nova_solicitacao1.jpg" name="Image12" width="230" height="28" border="0"></a></li>
-->
<!--    <li><a href="cadastro_empresa.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image13','','imagens/painel_empresa/btn_quero_anunciar2.jpg',1)"><img src="imagens/painel_empresa/btn_quero_anunciar1.jpg" name="Image13" width="230" height="28" border="0" id="Image13" /></a></li> -->         
    </ul>
    </td>
    </tr>
</table>
    <table width="100%" border="0" cellspacing="0" cellpadding="0" id="menu_comprador">
        <tr>
            <td>
                <ul>
                    <li><a href="restrito_minha_solicitacao_comprador.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image11','','imagens/painel_comprador/btn_minha_solicitacao2.jpg',1)"><img src="imagens/painel_comprador/btn_minha_solicitacao1.jpg" name="Image11" width="230" height="28" border="0"></a></li>
                    <li><a href="nova_solicitacao.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image12','','imagens/painel_comprador/btn_nova_solicitacao2.jpg',1)"><img src="imagens/painel_comprador/btn_nova_solicitacao1.jpg" name="Image12" width="230" height="28" border="0"></a></li>
                    <!--<li><a href="restrito_altera_senha_comprador.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image10','','imagens/painel_comprador/btn_altera_senha2.jpg',1)"><img src="imagens/painel_comprador/btn_altera_senha1.jpg" name="Image10" width="230" height="28" border="0"></a></li>-->
                    <!--<li><a href="restrito_altera_dados_comprador.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image9','','imagens/painel_comprador/btn_alterar_dados2.jpg',1)"><img src="imagens/painel_comprador/btn_alterar_dados1.jpg" name="Image9" width="230" height="28" border="0"></a></li>-->
                    <!--<li><a href="lista_busca_solicitacoes.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image15','','imagens/painel_comprador/btn_acompanhar_solicitacao2.jpg',1)"><img src="imagens/painel_comprador/btn_acompanhar_solicitacao1.jpg" name="Image15" width="230" height="28" border="0" id="Image15" /></a></li>
                    <li><a href="restrito_comprador_atualizar_descricao.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image16','','imagens/painel_comprador/btn_alterar_descricao2.jpg',1)"><img src="imagens/painel_comprador/btn_alterar_descricao1.jpg" name="Image16" width="230" height="28" border="0" id="Image16" /></a></li>
                    <li><a href="restrito_comprador_atualizar_logo.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image17','','imagens/painel_comprador/btn_atualizar_logotipo2.jpg',1)"><img src="imagens/painel_comprador/btn_atualizar_logotipo1.jpg" name="Image17" width="230" height="28" border="0" id="Image17" /></a></li>
                    <li><a href="restrito_comprador_atualizar_fotos.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image18','','imagens/painel_comprador/btn_atualizar_fotos2.jpg',1)"><img src="imagens/painel_comprador/btn_atualizar_fotos1.jpg" name="Image18" width="230" height="28" border="0" id="Image18" /></a></li>-->                      <!-- <li><a href="lista_planos.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image19','','imagens/painel_comprador/btn_alterar_plano2.jpg',1)"><img src="imagens/painel_comprador/btn_alterar_plano1.jpg" name="Image19" width="230" height="28" border="0" id="Image19" /></a></li>-->
                    <!--<li><a href="restrito_comprador_avaliacao.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image20','','imagens/painel_comprador/btn_avaliacao2.jpg',1)"><img src="imagens/painel_comprador/btn_avaliacao1.jpg" name="Image20" width="230" height="28" border="0" id="Image20" /></a></li>-->
                    <!--<li><a href="restrito_comprador_atualizar_limite.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image21','','imagens/painel_comprador/btn_limite_plano2.jpg',1)"><img src="imagens/painel_comprador/btn_limite_plano1.jpg" name="Image21" width="230" height="28" border="0" id="Image21" /></a></li>-->
                    <!--<li><a href="cadastro_empresa_1.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image7','','imagens/painel_empresa/btn_quero_anunciar2.jpg',1)"><img src="imagens/painel_empresa/btn_quero_anunciar1.jpg" name="Image7" width="230" height="28" border="0"></a></li>-->
                </ul>
            </td>
        </tr>
    </table>
<ul>
    <li><a href="sair.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image8','','imagens/painel_empresa/btn_sair2.jpg',1)"><img src="imagens/painel_empresa/btn_sair1.jpg" name="Image8" width="47" height="28" border="0" id="Image8" /></a></li>
</ul>


