<%@page contentType="text/html" pageEncoding="UTF-8"%>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td>&nbsp;</td>
              </tr>
               <tr>
                <td align="center" class="menu_rodape linha_rodape">
                 <p><a href="empresa.jsp">A EMPRESA </a> | <a href="termos.jsp"> TERMOS DE USO </a> |  <a href="politica.jsp">POLÍTICA DE PRIVACIDADE</a> | <a href="como_funciona.jsp">COMO FUNCIONA</a> </p>
                </td>
              </tr>
              <tr>
                <td align="center" class="copy">
                 <p>O uso deste site web implica na aceitação dos Termos e Condições Gerais e das Políticas de Privacidade do MelhorOferta.net<br />
                    Copyright 2012 MelhorOferta.net</p>
                </td>
              </tr>
              <tr>
            </tr>
            </table>
            <script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-3435437-3");
pageTracker._trackPageview();
} catch(err) {}</script>