<table width="213" border="0" cellspacing="0" cellpadding="0">
    <tbody>
        <tr>
            <td><img src="imagens/boxcadastre-se/cadastre_cima.jpg" alt="Cadastre-se" width="214" height="94" border="0" title="Cadastre-se"></td>
        </tr>
        <tr>
            <td><a href="cadastro_usuario.jsp"><img src="imagens/boxcadastre-se/cadastre_bt_cima.jpg" alt="Cadastre-se" width="214" height="39" border="0" title="Cadastre-se"></a></td>
        </tr>
        <tr>
            <td><img src="imagens/boxcadastre-se/cadastre_baixo.jpg" alt="Cadastre-se" width="214" height="69" border="0" title="Cadastre-se"></td>
        </tr>
        <tr>
            <td><a href="cadastro_empresa.jsp"><img src="imagens/boxcadastre-se/cadastre_bt_bx.jpg" width="214" height="42" alt="Cadastre-se" title="Cadastre-se" border="0"></a></td>
        </tr>
        <tr>
            <td><a href="como_funciona.jsp"><img src="imagens/como_funciona.jpg" width="173" height="185" alt="Como Funciona" title="Como Funciona"  border="0"/></a></td>
        </tr>
    </tbody>
</table>