<%@page contentType="text/html" pageEncoding="UTF-8"%>
<script type="text/javascript">
<!--
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script><body onLoad="MM_preloadImages('../imagens/painel_empresa/btn_quero_anunciar2.jpg','imagens/painel_empresa/btn_sair2.jpg','../imagens/painel_empresa/btn_alterar_categorias2.jpg','imagens/painel_empresa/btn_alterar_dados2.jpg','imagens/painel_empresa/btn_avaliacao2.jpg','imagens/painel_empresa/btn_alterar_descricao2.jpg')">

  						 <table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td>
                           <ul>
                         <li><a href="restrito_acompanhar_solicitacao_comprador.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image15','','imagens/painel_empresa/btn_acompanhar_solicitacao2.jpg',1)"><img src="imagens/painel_empresa/btn_acompanhar_solicitacao1.jpg" name="Image15" width="230" height="28" border="0" id="Image15" /></a></li>
                         <li><a href="restrito_vendedor_minhas_solicitacoes.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image40','','imagens/painel_empresa/btn_solicitacao_ganha_h.jpg',1)"><img src="imagens/painel_empresa/btn_solicitacao_ganha.jpg" name="Image40" width="230" height="28" border="0"></a></li>
                         <li><a href="restrito_vendedor_avaliacao.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image20','','imagens/painel_empresa/btn_avaliacao2.jpg',1)"><img src="imagens/painel_empresa/btn_avaliacao1.jpg" name="Image20" width="230" height="28" border="0" id="Image20" /></a></li>
	                     <li><a href="restrito_altera_categ_empresa.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image12','','imagens/painel_empresa/btn_alterar_categorias2.jpg',1)"><img src="imagens/painel_empresa/btn_alterar_categorias1.jpg" name="Image12" width="230" height="28" border="0"></a></li>
                         <li><a href="restrito_vendedor_atualizar_limite.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image21','','imagens/painel_empresa/btn_limite_plano2.jpg',1)"><img src="imagens/painel_empresa/btn_limite_plano1.jpg" name="Image21" width="230" height="28" border="0" id="Image21" /></a></li>
                         <li><a href="lista_planos.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image19','','imagens/painel_empresa/btn_alterar_plano2.jpg',1)"><img src="imagens/painel_empresa/btn_alterar_plano1.jpg" name="Image19" width="230" height="28" border="0" id="Image19" /></a></li>
                         <li><a href="restrito_vendedor_atualizar_descricao.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image16','','imagens/painel_empresa/btn_alterar_descricao2.jpg',1)"><img src="imagens/painel_empresa/btn_alterar_descricao1.jpg" name="Image16" width="230" height="28" border="0" id="Image16" /></a></li>
                         <li><a href="restrito_vendedor_atualizar_logo.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image17','','imagens/painel_empresa/btn_atualizar_logotipo2.jpg',1)"><img src="imagens/painel_empresa/btn_atualizar_logotipo1.jpg" name="Image17" width="230" height="28" border="0" id="Image17" /></a></li>
                         <li><a href="restrito_vendedor_atualizar_fotos.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image18','','imagens/painel_empresa/btn_atualizar_fotos2.jpg',1)"><img src="imagens/painel_empresa/btn_atualizar_fotos1.jpg" name="Image18" width="230" height="28" border="0" id="Image18" /></a></li>
                         <li><a href="restrito_altera_dados_empresa.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image9','','imagens/painel_empresa/btn_alterar_dados2.jpg',1)"><img src="imagens/painel_empresa/btn_alterar_dados1.jpg" name="Image9" width="230" height="28" border="0"></a></li>
                          <li><a href="restrito_altera_senha_empresa.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image10','','imagens/painel_empresa/btn_alterar_senha2.jpg',1)"><img src="imagens/painel_empresa/btn_alterar_senha1.jpg" name="Image10" width="230" height="28" border="0"></a></li>
<!--                         <li><a href="detalhes_solicitacoes.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image11','','imagens/painel_empresa/btn_minha_solicitacao2.jpg',1)"><img src="imagens/painel_empresa/btn_minha_solicitacao1.jpg" name="Image11" width="230" height="28" border="0"></a></li>
                         <li><a href="nova_solicitacao.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image12','','imagens/painel_empresa/btn_nova_solicitacao2.jpg',1)"><img src="imagens/painel_empresa/btn_nova_solicitacao1.jpg" name="Image12" width="230" height="28" border="0"></a></li>
-->
<!--                         <li><a href="cadastro_empresa.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image13','','imagens/painel_empresa/btn_quero_anunciar2.jpg',1)"><img src="imagens/painel_empresa/btn_quero_anunciar1.jpg" name="Image13" width="230" height="28" border="0" id="Image13" /></a></li>
-->                         <li><a href="sair.jsp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image8','','imagens/painel_empresa/btn_sair2.jpg',1)"><img src="imagens/painel_empresa/btn_sair1.jpg" name="Image8" width="47" height="28" border="0" id="Image8" /></a></li>
                         </ul>
                         
                             </td>
                          </tr>
                        </table>