<%@page contentType="text/html" pageEncoding="UTF-8"%>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                <td>
 				</td>
                </tr>
                 <tr>
                   <td align="center" valign="bottom"><img src="imagens/identificacao/sacola_topo.jpg" width="162" height="100" /></td>
                 </tr>
                 <tr>
                   <td align="center" valign="top"><img src="imagens/identificacao/sacola_rodape.jpg" width="162" height="103" /></td>
                 </tr>
        
                 <tr>
                   <td align="center" valign="top">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td>
                                         <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="35"><img src="imagens/titu_tags.jpg" width="32" height="9" alt="Tags" title="tags" /></td>
                                            <td class="back_tag">&nbsp;</td>
                                     	 </tr>
                                     </table>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td width="213">
                                         <%@include file="nuvem_tags.jsp" %>
                                        </td>
                                      </tr>
                                    </table>
                   </td>
                 </tr>
            </table>