<%@page contentType="text/html" pageEncoding="UTF-8"%>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="150" class="logo"><a href="index.jsp"><img src="imagens/topo/logo.jpg" width="150" height="126" alt="Melhor Oferta" title="Melhor Oferta" border="0" /></a></td>
            <td width="22">&nbsp;</td>
            <td width="624" valign="bottom">
             <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td align="center"><!-- Anúncio Dinâmico LOMADEE - INÍCIO -->
<div style="width:468px; height:60px; overflow:hidden;">
<div style="overflow:hidden;">
<script language="javascript"
 src="http://ivitrine.buscape.com/bpadsvar.js"></script>
<script language="javascript" ><!--
buscapeads_afiliado = "44566327";
buscapeads_tipo_cliente = "2";
buscapeads_vitrine_local = "BR";
buscapeads_site_origem = "10404465";
buscapeads_vitrine_vers = "1.23";
buscapeads_formato = "468x60";
buscapeads_id_keyword = "250654";
buscapeads_txt_keyword = "";
buscapeads_tipo_canal = "2";
buscapeads_categorias = "";
buscapeads_excluir = "3";
buscapeads_idioma = "pt";
buscapeads_pais = "BR";
buscapeads_area = "";
buscapeads_estado = "";
buscapeads_cidade = "";
buscapeads_cep = "";
//--></script>
<script language="javascript"
 src="http://ivitrine.buscape.com/bpads.js"></script></div>
<a href="http://www.lomadee.com/"><font size="1"><div align="right">
Cadastre-se gratuitamente como comprador para receber as melhores ofertas.</div></font></a></div>
<!-- Anúncio Dinâmico LOMADEE - FIM --></td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                  </tr>
                  <tr>
                    <td class="menu">
                    <!--inicio menu-->
                     <ul>
                        <li><a href="cadastro_usuario.jsp"><img src="imagens/topo/bt_cadastro_comprador.jpg" width="109" height="42" alt="Cadastro Comprador" title="Cadastro Comprador" border="0" /></a></li>
                        <li><a href="cadastro_empresa.jsp"><img src="imagens/topo/bt_cadastro_vendedor.jpg" width="111" height="42" alt="Cadastro Vendedor" title="Cadastro Vendedor" border="0" /></a></li>
                        <li><a href="buscar_solicitacoes.jsp"><img src="imagens/topo/bt_buscar_solicitacoes.jpg" width="111" height="42" alt="Buscar Solicitaes" title="Buscar Solicitaes" border="0" /></a></li>
                        <li><a href="quero_melhor_oferta.jsp"><img src="imagens/topo/bt_quero.jpg" width="130" height="42" alt="Quero a Melhor Oferta" title="Quero a Melhor Oferta" border="0" /></a></li>
                        <!--<li><a href="nova_solicitacao.jsp"><img src="imagens/topo/bt_quero.jpg" width="130" height="42" alt="Quero a Melhor Oferta" title="Quero a Melhor Oferta" border="0" /></a></li>-->
                        <li><a href="minha_conta.jsp"><img src="imagens/topo/bt_conta.jpg" width="77" height="42" alt="Minha Conta" title="Minha Conta" border="0" /></a></li>
                        <li><a href="contato.jsp"><img src="imagens/topo/bt_contato.jpg" width="86" height="42" alt="Contato" title="Contato" border="0" /></a></li>
                    </ul>
                    <!--fim menu-->
                    </td>
                  </tr>
              </table>
            </td>
            <td width="159">&nbsp;</td>
            <td valign="bottom"><a href="index.jsp"></a></td>
          </tr>
          
        </table>
    </td>
  </tr>
  <tr>
    <td class="back" height="7"></td>
  </tr>
</table>
