package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA



/**
 * Avaliacao generated by hbm2java
 */
public class Avaliacao  implements java.io.Serializable {


     private AvaliacaoId id;
     private Solicitacao solicitacao;
     private String observacao;
     private Integer positivo;
     private Integer negativo;

    public Avaliacao() {
    }

	
    public Avaliacao(AvaliacaoId id) {
        this.id = id;
    }
    public Avaliacao(AvaliacaoId id, Solicitacao solicitacao, String observacao, Integer positivo, Integer negativo) {
       this.id = id;
       this.solicitacao = solicitacao;
       this.observacao = observacao;
       this.positivo = positivo;
       this.negativo = negativo;
    }
   
    public AvaliacaoId getId() {
        return this.id;
    }
    
    public void setId(AvaliacaoId id) {
        this.id = id;
    }
    public Solicitacao getSolicitacao() {
        return this.solicitacao;
    }
    
    public void setSolicitacao(Solicitacao solicitacao) {
        this.solicitacao = solicitacao;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Integer getPositivo() {
        return this.positivo;
    }
    
    public void setPositivo(Integer positivo) {
        this.positivo = positivo;
    }
    public Integer getNegativo() {
        return this.negativo;
    }
    
    public void setNegativo(Integer negativo) {
        this.negativo = negativo;
    }




}


