package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Avaliacoes generated by hbm2java
 */
public class Avaliacoes  implements java.io.Serializable {


     private Integer navaliacao;
     private Empresas nempresa;
     private Solicitacoes nsolicitacao;
     private Usuarios nusuario;
     private Integer avaliado;
     private Integer atendimento;
     private Integer qualidade;
     private Integer comunicacao;
     private Integer econfiabilidade;
     private Integer uconfiabilidade;
     private String comentario;
     private Integer ativo;
     private Date ua;

    public Avaliacoes() {
    }

    public Avaliacoes(Empresas nempresa, Solicitacoes nsolicitacao, Usuarios nusuario, Integer avaliado, Integer atendimento, Integer qualidade, Integer comunicacao, Integer econfiabilidade, Integer uconfiabilidade, String comentario, Integer ativo, Date ua) {
       this.nempresa = nempresa;
       this.nsolicitacao = nsolicitacao;
       this.nusuario = nusuario;
       this.avaliado = avaliado;
       this.atendimento = atendimento;
       this.qualidade = qualidade;
       this.comunicacao = comunicacao;
       this.econfiabilidade = econfiabilidade;
       this.uconfiabilidade = uconfiabilidade;
       this.comentario = comentario;
       this.ativo = ativo;
       this.ua = ua;
    }
   
    public Integer getNavaliacao() {
        return this.navaliacao;
    }
    
    public void setNavaliacao(Integer navaliacao) {
        this.navaliacao = navaliacao;
    }
    public Empresas getNempresa() {
        return this.nempresa;
    }
    
    public void setNempresa(Empresas nempresa) {
        this.nempresa = nempresa;
    }
    public Solicitacoes getNsolicitacao() {
        return this.nsolicitacao;
    }
    
    public void setNsolicitacao(Solicitacoes nsolicitacao) {
        this.nsolicitacao = nsolicitacao;
    }
    public Usuarios getNusuario() {
        return this.nusuario;
    }
    
    public void setNusuario(Usuarios nusuario) {
        this.nusuario = nusuario;
    }
    public Integer getAvaliado() {
        return this.avaliado;
    }
    
    public void setAvaliado(Integer avaliado) {
        this.avaliado = avaliado;
    }
    public Integer getAtendimento() {
        return this.atendimento;
    }
    
    public void setAtendimento(Integer atendimento) {
        this.atendimento = atendimento;
    }
    public Integer getQualidade() {
        return this.qualidade;
    }
    
    public void setQualidade(Integer qualidade) {
        this.qualidade = qualidade;
    }
    public Integer getComunicacao() {
        return this.comunicacao;
    }
    
    public void setComunicacao(Integer comunicacao) {
        this.comunicacao = comunicacao;
    }
    public Integer getEconfiabilidade() {
        return this.econfiabilidade;
    }
    
    public void setEconfiabilidade(Integer econfiabilidade) {
        this.econfiabilidade = econfiabilidade;
    }
    public Integer getUconfiabilidade() {
        return this.uconfiabilidade;
    }
    
    public void setUconfiabilidade(Integer uconfiabilidade) {
        this.uconfiabilidade = uconfiabilidade;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Integer getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Integer ativo) {
        this.ativo = ativo;
    }
    public Date getUa() {
        return this.ua;
    }
    
    public void setUa(Date ua) {
        this.ua = ua;
    }




}


