package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA

import java.sql.Date;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private Integer ncategoria;
     private String nome;
     private Integer ativa;
     private Date dataCriacao;
     private String tipo;
     private Vendedorcategorias vendedorcategorias;
     private Subcategorias subcategorias;

    public Categorias() {
    }

    public Categorias(String nome, Integer ativa, Date dataCriacao, String tipo, Set vendedorcategoriases, Set subcategorias) {
       this.nome = nome;
       this.ativa = ativa;
       this.dataCriacao = dataCriacao;
       this.tipo = tipo;
       this.vendedorcategorias = (Vendedorcategorias) vendedorcategorias;
       this.subcategorias = (Subcategorias) subcategorias;
    }
   
    public Integer getNcategoria() {
        return this.ncategoria;
    }
    
    public void setNcategoria(Integer ncategoria) {
        this.ncategoria = ncategoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getAtiva() {
        return this.ativa;
    }
    
    public void setAtiva(Integer ativa) {
        this.ativa = ativa;
    }
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    
    public void setSubcategorias(Set subcategorias) {
        this.setSubcategorias(subcategorias);
    }

    /**
     * @param vendedorcategoriases the vendedorcategoriases to set
     */
    public void setVendedorcategoriases(Vendedorcategorias vendedorcategoriases) {
        this.setVendedorcategorias(vendedorcategoriases);
    }

    /**
     * @param subcategorias the subcategorias to set
     */
    public void setSubcategorias(Subcategorias subcategorias) {
        this.subcategorias = subcategorias;
    }

    /**
     * @return the vendedorcategorias
     */
    public Vendedorcategorias getVendedorcategorias() {
        return vendedorcategorias;
    }

    /**
     * @param vendedorcategorias the vendedorcategorias to set
     */
    public void setVendedorcategorias(Vendedorcategorias vendedorcategorias) {
        this.vendedorcategorias = vendedorcategorias;
    }

    /**
     * @return the subcategorias
     */
    public Subcategorias getSubcategorias() {
        return subcategorias;
    }

    




}


