package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cidades generated by hbm2java
 */
public class Cidades  implements java.io.Serializable {


     private int cdCidade;
     private Uf uf;
     private String dsCidadeNome;
     private Set bairroses = new HashSet(0);

    public Cidades() {
    }

	
    public Cidades(int cdCidade) {
        this.cdCidade = cdCidade;
    }
    public Cidades(int cdCidade, Uf uf, String dsCidadeNome, Set bairroses) {
       this.cdCidade = cdCidade;
       this.uf = uf;
       this.dsCidadeNome = dsCidadeNome;
       this.bairroses = bairroses;
    }
   
    public int getCdCidade() {
        return this.cdCidade;
    }
    
    public void setCdCidade(int cdCidade) {
        this.cdCidade = cdCidade;
    }
    public Uf getUf() {
        return this.uf;
    }
    
    public void setUf(Uf uf) {
        this.uf = uf;
    }
    public String getDsCidadeNome() {
        return this.dsCidadeNome;
    }
    
    public void setDsCidadeNome(String dsCidadeNome) {
        this.dsCidadeNome = dsCidadeNome;
    }
    public Set getBairroses() {
        return this.bairroses;
    }
    
    public void setBairroses(Set bairroses) {
        this.bairroses = bairroses;
    }




}


