package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA


import java.sql.Date;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private Integer nempresa;
     private Planos nplano;
     private String razaoSocial;
     private String nomeFantasia;
     private String ramoAtividade;
     private String responsavel;
     private String tipo;
     private String cnpj;
     private String cpf;
     private String cep;
     private String endereco;
     private String numero;
     private String complemento;
     private String bairro;
     private String estado;
     private String cidade;
     private String telefone;
     private String email;
     private String site;
     private String login;
     private String senha;
     private String palavrasChaves;
     private String mapa;
     private String descricao;
     private Integer ativa;
     private Date ua;

    public Empresas() {
    }

    public Empresas(Planos nplano, String razaoSocial, String nomeFantasia, String ramoAtividade, String responsavel, String tipo, String cnpj, String cpf, String cep, String endereco, String numero, String complemento, String bairro, String estado, String cidade, String telefone, String email, String site, String login, String senha, String palavrasChaves, String mapa, String descricao, Integer ativa, Date ua) {
       this.nplano = nplano;
       this.razaoSocial = razaoSocial;
       this.nomeFantasia = nomeFantasia;
       this.ramoAtividade = ramoAtividade;
       this.responsavel = responsavel;
       this.tipo = tipo;
       this.cnpj = cnpj;
       this.cpf = cpf;
       this.cep = cep;
       this.endereco = endereco;
       this.numero = numero;
       this.complemento = complemento;
       this.bairro = bairro;
       this.estado = estado;
       this.cidade = cidade;
       this.telefone = telefone;
       this.email = email;
       this.site = site;
       this.login = login;
       this.senha = senha;
       this.palavrasChaves = palavrasChaves;
       this.mapa = mapa;
       this.descricao = descricao;
       this.ativa = ativa;
       this.ua = ua;
    }
   
    public Integer getNempresa() {
        return this.nempresa;
    }
    
    public void setNempresa(Integer nempresa) {
        this.nempresa = nempresa;
    }
    public Planos getNplano() {
        return this.nplano;
    }
    
    public void setNplano(Planos nplano) {
        this.nplano = nplano;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }
    public String getRamoAtividade() {
        return this.ramoAtividade;
    }
    
    public void setRamoAtividade(String ramoAtividade) {
        this.ramoAtividade = ramoAtividade;
    }
    public String getResponsavel() {
        return this.responsavel;
    }
    
    public void setResponsavel(String responsavel) {
        this.responsavel = responsavel;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getPalavrasChaves() {
        return this.palavrasChaves;
    }
    
    public void setPalavrasChaves(String palavrasChaves) {
        this.palavrasChaves = palavrasChaves;
    }
    public String getMapa() {
        return this.mapa;
    }
    
    public void setMapa(String mapa) {
        this.mapa = mapa;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Integer getAtiva() {
        return this.ativa;
    }
    
    public void setAtiva(Integer ativa) {
        this.ativa = ativa;
    }
    public Date getUa() {
        return this.ua;
    }
    
    public void setUa(Date ua) {
        this.ua = ua;
    }




}


