package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Empresacategorias generated by hbm2java
 */
public class Empresacategorias  implements java.io.Serializable {


     private Integer nempresaCategoria;
     private Empresas nempresa;
     private Categorias ncategoria;
     private Subcategorias nsubCategoria;
     private Date ua;

    public Empresacategorias() {
    }

    public Empresacategorias(Empresas nempresa, Categorias ncategoria, Subcategorias nsubCategoria, Date ua) {
       this.nempresa = nempresa;
       this.ncategoria = ncategoria;
       this.nsubCategoria = nsubCategoria;
       this.ua = ua;
    }
   
    public Integer getNempresaCategoria() {
        return this.nempresaCategoria;
    }
    
    public void setNempresaCategoria(Integer nempresaCategoria) {
        this.nempresaCategoria = nempresaCategoria;
    }
    public Empresas getNempresa() {
        return this.nempresa;
    }
    
    public void setNempresa(Empresas nempresa) {
        this.nempresa = nempresa;
    }
    public Categorias getNcategoria() {
        return this.ncategoria;
    }
    
    public void setNcategoria(Categorias ncategoria) {
        this.ncategoria = ncategoria;
    }
    public Subcategorias getNsubCategoria() {
        return this.nsubCategoria;
    }
    
    public void setNsubCategoria(Subcategorias nsubCategoria) {
        this.nsubCategoria = nsubCategoria;
    }
    public Date getUa() {
        return this.ua;
    }
    
    public void setUa(Date ua) {
        this.ua = ua;
    }




}


