package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Interacoes generated by hbm2java
 */
public class Interacoes  implements java.io.Serializable {


     private Long ninteracao;
     private Solicitacoes nsolicitacao;
     private Usuarios nusuario;
     private Empresas nempresa;
     private Date data;
     private String texto;
     private Double valor;
     private Integer ativo;
     private Date ua;

    public Interacoes() {
    }

	
    public Interacoes(Solicitacoes nsolicitacao) {
        this.nsolicitacao = nsolicitacao;
    }
    public Interacoes(Solicitacoes nsolicitacao, Usuarios nusuario, Empresas nempresa, Date data, String texto, Double valor, Integer ativo, Date ua) {
       this.nsolicitacao = nsolicitacao;
       this.nusuario = nusuario;
       this.nempresa = nempresa;
       this.data = data;
       this.texto = texto;
       this.valor = valor;
       this.ativo = ativo;
       this.ua = ua;
    }
   
    public Long getNinteracao() {
        return this.ninteracao;
    }
    
    public void setNinteracao(Long ninteracao) {
        this.ninteracao = ninteracao;
    }
    public Solicitacoes getNsolicitacao() {
        return this.nsolicitacao;
    }
    
    public void setNsolicitacao(Solicitacoes nsolicitacao) {
        this.nsolicitacao = nsolicitacao;
    }
    public Usuarios getNusuario() {
        return this.nusuario;
    }
    
    public void setNusuario(Usuarios nusuario) {
        this.nusuario = nusuario;
    }
    public Empresas getNempresa() {
        return this.nempresa;
    }
    
    public void setNempresa(Empresas nempresa) {
        this.nempresa = nempresa;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public Integer getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Integer ativo) {
        this.ativo = ativo;
    }
    public Date getUa() {
        return this.ua;
    }
    
    public void setUa(Date ua) {
        this.ua = ua;
    }




}


