package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA



/**
 * Logradouros generated by hbm2java
 */
public class Logradouros  implements java.io.Serializable {


     private int cdLogradouro;
     private Bairros bairros;
     private Integer cdTipoLogradouro;
     private String dsLogradouroNome;
     private String noLogradouroCep;

    public Logradouros() {
    }

	
    public Logradouros(int cdLogradouro) {
        this.cdLogradouro = cdLogradouro;
    }
    public Logradouros(int cdLogradouro, Bairros bairros, Integer cdTipoLogradouro, String dsLogradouroNome, String noLogradouroCep) {
       this.cdLogradouro = cdLogradouro;
       this.bairros = bairros;
       this.cdTipoLogradouro = cdTipoLogradouro;
       this.dsLogradouroNome = dsLogradouroNome;
       this.noLogradouroCep = noLogradouroCep;
    }
   
    public int getCdLogradouro() {
        return this.cdLogradouro;
    }
    
    public void setCdLogradouro(int cdLogradouro) {
        this.cdLogradouro = cdLogradouro;
    }
    public Bairros getBairros() {
        return this.bairros;
    }
    
    public void setBairros(Bairros bairros) {
        this.bairros = bairros;
    }
    public Integer getCdTipoLogradouro() {
        return this.cdTipoLogradouro;
    }
    
    public void setCdTipoLogradouro(Integer cdTipoLogradouro) {
        this.cdTipoLogradouro = cdTipoLogradouro;
    }
    public String getDsLogradouroNome() {
        return this.dsLogradouroNome;
    }
    
    public void setDsLogradouroNome(String dsLogradouroNome) {
        this.dsLogradouroNome = dsLogradouroNome;
    }
    public String getNoLogradouroCep() {
        return this.noLogradouroCep;
    }
    
    public void setNoLogradouroCep(String noLogradouroCep) {
        this.noLogradouroCep = noLogradouroCep;
    }




}


