package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Pagseguro generated by hbm2java
 */
public class Pagseguro  implements java.io.Serializable {


     private Integer id;
     private String status;
     private Empresas idEmpresa;
     private String idTransacao;
     private String tipoPagamento;
     private Date dataTransacao;

    public Pagseguro() {
    }

    public Pagseguro(String status, Empresas idEmpresa, String idTransacao, String tipoPagamento, Date dataTransacao) {
       this.status = status;
       this.idEmpresa = idEmpresa;
       this.idTransacao = idTransacao;
       this.tipoPagamento = tipoPagamento;
       this.dataTransacao = dataTransacao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Empresas getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Empresas idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getIdTransacao() {
        return this.idTransacao;
    }
    
    public void setIdTransacao(String idTransacao) {
        this.idTransacao = idTransacao;
    }
    public String getTipoPagamento() {
        return this.tipoPagamento;
    }
    
    public void setTipoPagamento(String tipoPagamento) {
        this.tipoPagamento = tipoPagamento;
    }
    public Date getDataTransacao() {
        return this.dataTransacao;
    }
    
    public void setDataTransacao(Date dataTransacao) {
        this.dataTransacao = dataTransacao;
    }




}


