package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Planos generated by hbm2java
 */
public class Planos  implements java.io.Serializable {


     private Integer nplano;
     private String nome;
     private String valor;
     private Integer negociacoes;
     private Integer npalavrasChave;
     private String qtCategoria;
     private String qtSubCategoria;
     private Integer nimagem;
     private String logotipo;
     private String mapaLocalizacao;
     private String descricao;
     private String ajuda;
     private Integer ativo;
     private Date ua;

    public Planos() {
    }

    public Planos(String nome, String valor, Integer negociacoes, Integer npalavrasChave, String qtCategoria, String qtSubCategoria, Integer nimagem, String logotipo, String mapaLocalizacao, String descricao, String ajuda, Integer ativo, Date ua) {
       this.nome = nome;
       this.valor = valor;
       this.negociacoes = negociacoes;
       this.npalavrasChave = npalavrasChave;
       this.qtCategoria = qtCategoria;
       this.qtSubCategoria = qtSubCategoria;
       this.nimagem = nimagem;
       this.logotipo = logotipo;
       this.mapaLocalizacao = mapaLocalizacao;
       this.descricao = descricao;
       this.ajuda = ajuda;
       this.ativo = ativo;
       this.ua = ua;
    }
   
    public Integer getNplano() {
        return this.nplano;
    }
    
    public void setNplano(Integer nplano) {
        this.nplano = nplano;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Integer getNegociacoes() {
        return this.negociacoes;
    }
    
    public void setNegociacoes(Integer negociacoes) {
        this.negociacoes = negociacoes;
    }
    public Integer getNpalavrasChave() {
        return this.npalavrasChave;
    }
    
    public void setNpalavrasChave(Integer npalavrasChave) {
        this.npalavrasChave = npalavrasChave;
    }
    public String getQtCategoria() {
        return this.qtCategoria;
    }
    
    public void setQtCategoria(String qtCategoria) {
        this.qtCategoria = qtCategoria;
    }
    public String getQtSubCategoria() {
        return this.qtSubCategoria;
    }
    
    public void setQtSubCategoria(String qtSubCategoria) {
        this.qtSubCategoria = qtSubCategoria;
    }
    public Integer getNimagem() {
        return this.nimagem;
    }
    
    public void setNimagem(Integer nimagem) {
        this.nimagem = nimagem;
    }
    public String getLogotipo() {
        return this.logotipo;
    }
    
    public void setLogotipo(String logotipo) {
        this.logotipo = logotipo;
    }
    public String getMapaLocalizacao() {
        return this.mapaLocalizacao;
    }
    
    public void setMapaLocalizacao(String mapaLocalizacao) {
        this.mapaLocalizacao = mapaLocalizacao;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getAjuda() {
        return this.ajuda;
    }
    
    public void setAjuda(String ajuda) {
        this.ajuda = ajuda;
    }
    public Integer getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Integer ativo) {
        this.ativo = ativo;
    }
    public Date getUa() {
        return this.ua;
    }
    
    public void setUa(Date ua) {
        this.ua = ua;
    }




}


