package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA


import java.sql.Date;

/**
 * Proposta generated by hbm2java
 */
public class Proposta  implements java.io.Serializable {


     private VendedorsolicitacaoId id;
     private Solicitacao solicitacao;
     private Vendedor vendedor;
     private Date dataInteracao;
     private String valor;
     private String observacao;
     private Integer melhoroferta;
     private Date prazoEntrega;
     private Usuario usuario;

    public Proposta() {
    }
    
    public Proposta(Solicitacao solicitacao) {
        this.solicitacao = solicitacao;
    }

    public Proposta(Solicitacao solicitacao, Vendedor vendedor, VendedorsolicitacaoId id, Usuario usuario) {
        this.usuario = usuario;
        this.id = id;
        this.solicitacao = solicitacao;
        this.vendedor = vendedor;
    }
	
    public Proposta(VendedorsolicitacaoId id, Solicitacao solicitacao, Vendedor vendedor) {
        this.id = id;
        this.solicitacao = solicitacao;
        this.vendedor = vendedor;
    }
    public Proposta(VendedorsolicitacaoId id, Solicitacao solicitacao, Vendedor vendedor, Date dataInteracao, String valor, String observacao, Integer melhoroferta) {
       this.id = id;
       this.solicitacao = solicitacao;
       this.vendedor = vendedor;
       this.dataInteracao = dataInteracao;
       this.valor = valor;
       this.observacao = observacao;
       this.melhoroferta = melhoroferta;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
   
    public VendedorsolicitacaoId getId() {
        return this.id;
    }
    
    public void setId(VendedorsolicitacaoId id) {
        this.id = id;
    }
    public Solicitacao getSolicitacao() {
        return this.solicitacao;
    }
    
    public void setSolicitacao(Solicitacao solicitacao) {
        this.solicitacao = solicitacao;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public Date getDataInteracao() {
        return this.dataInteracao;
    }
    
    public void setDataInteracao(Date dataInteracao) {
        this.dataInteracao = dataInteracao;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Integer getMelhoroferta() {
        return this.melhoroferta;
    }
    
    public void setMelhoroferta(Integer melhoroferta) {
        this.melhoroferta = melhoroferta;
    }

    /**
     * @return the prazoEntrega
     */
    public Date getPrazoEntrega() {
        return prazoEntrega;
    }

    /**
     * @param prazoEntrega the prazoEntrega to set
     */
    public void setPrazoEntrega(Date prazoEntrega) {
        this.prazoEntrega = prazoEntrega;
    }




}


