package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Propostas generated by hbm2java
 */
public class Propostas  implements java.io.Serializable {


     private Integer nproposta;
     private Empresas nempresa;
     private Solicitacoes nsolicitacao;
     private String texto;
     private Integer ativo;
     private Date ua;

    public Propostas() {
    }

    public Propostas(Empresas nempresa, Solicitacoes nsolicitacao, String texto, Integer ativo, Date ua) {
       this.nempresa = nempresa;
       this.nsolicitacao = nsolicitacao;
       this.texto = texto;
       this.ativo = ativo;
       this.ua = ua;
    }
   
    public Integer getNproposta() {
        return this.nproposta;
    }
    
    public void setNproposta(Integer nproposta) {
        this.nproposta = nproposta;
    }
    public Empresas getNempresa() {
        return this.nempresa;
    }
    
    public void setNempresa(Empresas nempresa) {
        this.nempresa = nempresa;
    }
    public Solicitacoes getNsolicitacao() {
        return this.nsolicitacao;
    }
    
    public void setNsolicitacao(Solicitacoes nsolicitacao) {
        this.nsolicitacao = nsolicitacao;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Integer getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Integer ativo) {
        this.ativo = ativo;
    }
    public Date getUa() {
        return this.ua;
    }
    
    public void setUa(Date ua) {
        this.ua = ua;
    }




}


