package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA



/**
 * SolicitacaosubcategoriasId generated by hbm2java
 */
public class SolicitacaosubcategoriasId  implements java.io.Serializable {


     private int nsolicitacao;
     private int nsubCategoria;

    public SolicitacaosubcategoriasId() {
    }

    public SolicitacaosubcategoriasId(int nsolicitacao, int nsubCategoria) {
       this.nsolicitacao = nsolicitacao;
       this.nsubCategoria = nsubCategoria;
    }
   
    public int getNsolicitacao() {
        return this.nsolicitacao;
    }
    
    public void setNsolicitacao(int nsolicitacao) {
        this.nsolicitacao = nsolicitacao;
    }
    public int getNsubCategoria() {
        return this.nsubCategoria;
    }
    
    public void setNsubCategoria(int nsubCategoria) {
        this.nsubCategoria = nsubCategoria;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SolicitacaosubcategoriasId) ) return false;
		 SolicitacaosubcategoriasId castOther = ( SolicitacaosubcategoriasId ) other; 
         
		 return (this.getNsolicitacao()==castOther.getNsolicitacao())
 && (this.getNsubCategoria()==castOther.getNsubCategoria());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNsolicitacao();
         result = 37 * result + this.getNsubCategoria();
         return result;
   }   


}


