package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA


import java.sql.Date;

/**
 * Solicitacoes generated by hbm2java
 */
public class Solicitacoes  implements java.io.Serializable {


     private Integer nsolicitacao;
     private Usuarios nusuario;
     private Categorias ncategoria;
     private Subcategorias nsubCategoria;
     private String produto;
     private Date prazo;
     private String descricao;
     private Integer status;
     private Empresas nempresaVencedora;
     private Date dataFinalizacao;
     private Integer contador;
     private Date ua;

    public Solicitacoes() {
    }

    public Solicitacoes(Usuarios nusuario, Categorias ncategoria, Subcategorias nsubCategoria, String produto, Date prazo, String descricao, Integer status, Empresas nempresaVencedora, Date dataFinalizacao, Integer contador, Date ua) {
       this.nusuario = nusuario;
       this.ncategoria = ncategoria;
       this.nsubCategoria = nsubCategoria;
       this.produto = produto;
       this.prazo = prazo;
       this.descricao = descricao;
       this.status = status;
       this.nempresaVencedora = nempresaVencedora;
       this.dataFinalizacao = dataFinalizacao;
       this.contador = contador;
       this.ua = ua;
    }
   
    public Integer getNsolicitacao() {
        return this.nsolicitacao;
    }
    
    public void setNsolicitacao(Integer nsolicitacao) {
        this.nsolicitacao = nsolicitacao;
    }
    public Usuarios getNusuario() {
        return this.nusuario;
    }
    
    public void setNusuario(Usuarios nusuario) {
        this.nusuario = nusuario;
    }
    public Categorias getNcategoria() {
        return this.ncategoria;
    }
    
    public void setNcategoria(Categorias ncategoria) {
        this.ncategoria = ncategoria;
    }
    public Subcategorias getNsubCategoria() {
        return this.nsubCategoria;
    }
    
    public void setNsubCategoria(Subcategorias nsubCategoria) {
        this.nsubCategoria = nsubCategoria;
    }
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }
    public Date getPrazo() {
        return this.prazo;
    }
    
    public void setPrazo(Date prazo) {
        this.prazo = prazo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Empresas getNempresaVencedora() {
        return this.nempresaVencedora;
    }
    
    public void setNempresaVencedora(Empresas nempresaVencedora) {
        this.nempresaVencedora = nempresaVencedora;
    }
    public Date getDataFinalizacao() {
        return this.dataFinalizacao;
    }
    
    public void setDataFinalizacao(Date dataFinalizacao) {
        this.dataFinalizacao = dataFinalizacao;
    }
    public Integer getContador() {
        return this.contador;
    }
    
    public void setContador(Integer contador) {
        this.contador = contador;
    }
    public Date getUa() {
        return this.ua;
    }
    
    public void setUa(Date ua) {
        this.ua = ua;
    }




}


