package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Solicitacaosubcategorias generated by hbm2java
 */
public class Solicitacaosubcategorias  implements java.io.Serializable {


     private SolicitacaosubcategoriasId id;
     private int ncategoria;
     private Date ua;

    public Solicitacaosubcategorias() {
    }

	
    public Solicitacaosubcategorias(SolicitacaosubcategoriasId id, int ncategoria) {
        this.id = id;
        this.ncategoria = ncategoria;
    }
    public Solicitacaosubcategorias(SolicitacaosubcategoriasId id, int ncategoria, Date ua) {
       this.id = id;
       this.ncategoria = ncategoria;
       this.ua = ua;
    }
   
    public SolicitacaosubcategoriasId getId() {
        return this.id;
    }
    
    public void setId(SolicitacaosubcategoriasId id) {
        this.id = id;
    }
    public int getNcategoria() {
        return this.ncategoria;
    }
    
    public void setNcategoria(int ncategoria) {
        this.ncategoria = ncategoria;
    }
    public Date getUa() {
        return this.ua;
    }
    
    public void setUa(Date ua) {
        this.ua = ua;
    }




}


