package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategorias  implements java.io.Serializable {


     private Integer nsubcategoria;
     private Categorias categorias;
     private String nome;
     private Integer ativa;
     private Date dataCriacao;
     private Set solicitacaos = new HashSet(0);

    public Subcategorias() {
    }

    public Subcategorias(Categorias categorias, String nome, Integer ativa, Date dataCriacao, Set solicitacaos) {
       this.categorias = categorias;
       this.nome = nome;
       this.ativa = ativa;
       this.dataCriacao = dataCriacao;
       this.solicitacaos = solicitacaos;
    }
   
    public Integer getNsubcategoria() {
        return this.nsubcategoria;
    }
    
    public void setNsubcategoria(Integer nsubcategoria) {
        this.nsubcategoria = nsubcategoria;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getAtiva() {
        return this.ativa;
    }
    
    public void setAtiva(Integer ativa) {
        this.ativa = ativa;
    }
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }
    public Set getSolicitacaos() {
        return this.solicitacaos;
    }
    
    public void setSolicitacaos(Set solicitacaos) {
        this.solicitacaos = solicitacaos;
    }




}


