package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA



/**
 * Teste generated by hbm2java
 */
public class Teste  implements java.io.Serializable {


     private Integer id;
     private String status;
     private Empresas idEmpresa;
     private String idTransacao;
     private String tipopagamento;

    public Teste() {
    }

    public Teste(String status, Empresas idEmpresa, String idTransacao, String tipopagamento) {
       this.status = status;
       this.idEmpresa = idEmpresa;
       this.idTransacao = idTransacao;
       this.tipopagamento = tipopagamento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Empresas getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Empresas idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getIdTransacao() {
        return this.idTransacao;
    }
    
    public void setIdTransacao(String idTransacao) {
        this.idTransacao = idTransacao;
    }
    public String getTipopagamento() {
        return this.tipopagamento;
    }
    
    public void setTipopagamento(String tipopagamento) {
        this.tipopagamento = tipopagamento;
    }




}


