package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Uf generated by hbm2java
 */
public class Uf  implements java.io.Serializable {


     private int cdUf;
     private String dsUfSigla;
     private String dsUfNome;
     private Set cidadeses = new HashSet(0);

    public Uf() {
    }

	
    public Uf(int cdUf) {
        this.cdUf = cdUf;
    }
    public Uf(int cdUf, String dsUfSigla, String dsUfNome, Set cidadeses) {
       this.cdUf = cdUf;
       this.dsUfSigla = dsUfSigla;
       this.dsUfNome = dsUfNome;
       this.cidadeses = cidadeses;
    }
   
    public int getCdUf() {
        return this.cdUf;
    }
    
    public void setCdUf(int cdUf) {
        this.cdUf = cdUf;
    }
    public String getDsUfSigla() {
        return this.dsUfSigla;
    }
    
    public void setDsUfSigla(String dsUfSigla) {
        this.dsUfSigla = dsUfSigla;
    }
    public String getDsUfNome() {
        return this.dsUfNome;
    }
    
    public void setDsUfNome(String dsUfNome) {
        this.dsUfNome = dsUfNome;
    }
    public Set getCidadeses() {
        return this.cidadeses;
    }
    
    public void setCidadeses(Set cidadeses) {
        this.cidadeses = cidadeses;
    }




}


