package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA


import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer nusuario;
     private String nome;
     private String tipo;
     private String sexo;
     private String email;
     private Integer ativa;  // 0 inativo - 1 ativo
     private Date datacriacao;
     private String login;
     private String senha;
     private String telefone;
     private String rua;
     private String cidade;
     private String estado;
     private String bairro;
     private String complemento;
     private String numero;
     private String cep;
     private Integer positivacoes;
     private Integer negativacoes;
     private String regiao;
     private String documento;
     private Date dtnascimento;
     private String celular;
     private String razao;
     private String fantasia;
     private String responsavel;
     private String contato;
    

    public Usuario() {
    }

    public Usuario(String responsavel, String razao, String fantasia, String celular, String nome,String tipo,String sexo,String email, Integer ativa, Date datacriacao, String login, String senha, String telefone,String rua ,String cidade, String estado, String bairro, String complemento, String numero,String cep, Integer positivacoes, Integer negativacoes, String regiao, String documento, Set vendedors, Set solicitacaos) {
       this.tipo = tipo;
       this.nome = email;
       this.email = email;
       this.ativa = ativa;
       this.datacriacao = datacriacao;
       this.login = login;
       this.senha = senha;
       this.telefone = telefone;
       this.rua = rua;
       this.cidade = cidade;
       this.estado = estado;
       this.bairro = bairro;
       this.complemento = complemento;
       this.numero = numero;
       this.cep = cep;
       this.positivacoes = positivacoes;
       this.negativacoes = negativacoes;
       this.regiao = regiao;
       this.documento = documento;
       this.celular = celular;
       this.razao = razao;
       this.fantasia = fantasia;
       this.responsavel = responsavel;

    }

    public String getResponsavel() {
        return responsavel;
    }

    public void setResponsavel(String responsavel) {
        this.responsavel = responsavel;
    }
    

    public String getFantasia() {
        return fantasia;
    }

    public void setFantasia(String fantasia) {
        this.fantasia = fantasia;
    }

    public String getRazao() {
        return razao;
    }

    public void setRazao(String razao) {
        this.razao = razao;
    }

    public String getCelular() {
        return celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }
   
    public Integer getNusuario() {
        return this.nusuario;
    }
    
    public void setNusuario(Integer nusuario) {
        this.nusuario = nusuario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getAtiva() {
        return this.ativa;
    }
    
    public void setAtiva(Integer ativa) {
        this.ativa = ativa;
    }
    public Date getDatacriacao() {
        return this.datacriacao;
    }
    
    public void setDatacriacao(Date datacriacao) {
        this.datacriacao = datacriacao;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
   
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public Integer getPositivacoes() {
        return this.positivacoes;
    }
    
    public void setPositivacoes(Integer positivacoes) {
        this.positivacoes = positivacoes;
    }
    public Integer getNegativacoes() {
        return this.negativacoes;
    }
    
    public void setNegativacoes(Integer negativacoes) {
        this.negativacoes = negativacoes;
    }
    public String getRegiao() {
        return this.regiao;
    }
    
    public void setRegiao(String regiao) {
        this.regiao = regiao;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }

    /**
     * @return the nome
     */
    public String getNome() {
        return nome;
    }

    /**
     * @param nome the nome to set
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * @return the sexo
     */
    public String getSexo() {
        return sexo;
    }

    /**
     * @param sexo the sexo to set
     */
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    /**
     * @return the rua
     */
    public String getRua() {
        return rua;
    }
   
 public void setRua(String rua) {
        this.rua = rua;
    }

    /**
     * @return the dtnascimento
     */
    public Date getDtnascimento() {
        return dtnascimento;
    }
    public void setDtnascimento(Date dtnascimento) {
        this.dtnascimento = dtnascimento;
    }

    /**
     * @return the contato
     */
    public String getContato() {
        return contato;
    }

    /**
     * @param contato the contato to set
     */
    public void setContato(String contato) {
        this.contato = contato;
    }


}


