package br.com.melhoroferta.entidades;
// Generated 17/02/2012 16:15:24 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer nusuario;
     private String nome;
     private String apelido;
     private String email;
     private String cpf;
     private Date dataNascimento;
     private String sexo;
     private String telefone;
     private String celular;
     private String cep;
     private String endereco;
     private String numero;
     private String complemento;
     private String bairro;
     private String regiao;
     private String estado;
     private String cidade;
     private String login;
     private String senha;
     private Integer ativo;
     private Date ua;

    public Usuarios() {
    }

    public Usuarios(String nome, String apelido, String email, String cpf, Date dataNascimento, String sexo, String telefone, String celular, String cep, String endereco, String numero, String complemento, String bairro, String regiao, String estado, String cidade, String login, String senha, Integer ativo, Date ua) {
       this.nome = nome;
       this.apelido = apelido;
       this.email = email;
       this.cpf = cpf;
       this.dataNascimento = dataNascimento;
       this.sexo = sexo;
       this.telefone = telefone;
       this.celular = celular;
       this.cep = cep;
       this.endereco = endereco;
       this.numero = numero;
       this.complemento = complemento;
       this.bairro = bairro;
       this.regiao = regiao;
       this.estado = estado;
       this.cidade = cidade;
       this.login = login;
       this.senha = senha;
       this.ativo = ativo;
       this.ua = ua;
    }
   
    public Integer getNusuario() {
        return this.nusuario;
    }
    
    public void setNusuario(Integer nusuario) {
        this.nusuario = nusuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getRegiao() {
        return this.regiao;
    }
    
    public void setRegiao(String regiao) {
        this.regiao = regiao;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Integer getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Integer ativo) {
        this.ativo = ativo;
    }
    public Date getUa() {
        return this.ua;
    }
    
    public void setUa(Date ua) {
        this.ua = ua;
    }




}


