package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.List;

/**
 * Vendedorcategorias generated by hbm2java
 */
public class Vendedorcategorias  implements java.io.Serializable {


     private VendedorcategoriasId id;
     private Vendedor vendedor;
     private Categorias categorias;
     private List<Categorias>listaCategorias;
     private Date dataCriacao;
     private Vendedorcategorias vendedorcategorias;

    public Vendedorcategorias getVendedorcategorias() {
        return vendedorcategorias;
    }

    public void setVendedorcategorias(Vendedorcategorias vendedorcategorias) {
        this.vendedorcategorias = vendedorcategorias;
    }
     
     

    public List<Categorias> getListaCategorias() {
        return listaCategorias;
    }

    public void setListaCategorias(List<Categorias> listaCategorias) {
        this.listaCategorias = listaCategorias;
    }
    
    public Vendedorcategorias() {
    }

	
    public Vendedorcategorias(VendedorcategoriasId id, Vendedor vendedor, Categorias categorias) {
        this.id = id;
        this.vendedor = vendedor;
        this.categorias = categorias;
    }
    
    
    public Vendedorcategorias(Vendedor vendedor, Categorias categorias) {
        this.vendedor = vendedor;
        this.categorias = categorias;
    }
    
    public Vendedorcategorias(VendedorcategoriasId id, Vendedor vendedor, Categorias categorias, Date dataCriacao) {
       this.id = id;
       this.vendedor = vendedor;
       this.categorias = categorias;
       this.dataCriacao = dataCriacao;
    }
   
    public VendedorcategoriasId getId() {
        return this.id;
    }
    
    public void setId(VendedorcategoriasId id) {
        this.id = id;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    public void setListaCategorias(Object attribute) {
        this.listaCategorias = listaCategorias;
    }




}


