package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA



/**
 * VendedorcategoriasId generated by hbm2java
 */
public class VendedorcategoriasId  implements java.io.Serializable {


     private int nvendedor;
     private int ncategoria;

    public VendedorcategoriasId() {
    }

    public VendedorcategoriasId(int nvendedor, int ncategoria) {
       this.nvendedor = nvendedor;
       this.ncategoria = ncategoria;
    }
   
    public int getNvendedor() {
        return this.nvendedor;
    }
    
    public void setNvendedor(int nvendedor) {
        this.nvendedor = nvendedor;
    }
    public int getNcategoria() {
        return this.ncategoria;
    }
    
    public void setNcategoria(int ncategoria) {
        this.ncategoria = ncategoria;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendedorcategoriasId) ) return false;
		 VendedorcategoriasId castOther = ( VendedorcategoriasId ) other; 
         
		 return (this.getNvendedor()==castOther.getNvendedor())
 && (this.getNcategoria()==castOther.getNcategoria());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNvendedor();
         result = 37 * result + this.getNcategoria();
         return result;
   }   


}


