package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA



/**
 * VendedorsolicitacaoId generated by hbm2java
 */
public class VendedorsolicitacaoId  implements java.io.Serializable {
//É A PROPOSTA QUE O VENDEDOR IRA FAZER AO CLIENTE

     private int nproposta;
     private int nvendedor;
     private int nsolicitacao;

    public VendedorsolicitacaoId() {
    }

    public VendedorsolicitacaoId(int nproposta, int nvendedor, int nsolicitacao) {
       this.nproposta = nproposta;
       this.nvendedor = nvendedor;
       this.nsolicitacao = nsolicitacao;
    }
   
    public int getNproposta() {
        return this.nproposta;
    }
    
    public void setNproposta(int nproposta) {
        this.nproposta = nproposta;
    }
    public int getNvendedor() {
        return this.nvendedor;
    }
    
    public void setNvendedor(int nvendedor) {
        this.nvendedor = nvendedor;
    }
    public int getNsolicitacao() {
        return this.nsolicitacao;
    }
    
    public void setNsolicitacao(int nsolicitacao) {
        this.nsolicitacao = nsolicitacao;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendedorsolicitacaoId) ) return false;
		 VendedorsolicitacaoId castOther = ( VendedorsolicitacaoId ) other; 
         
		 return (this.getNproposta()==castOther.getNproposta())
 && (this.getNvendedor()==castOther.getNvendedor())
 && (this.getNsolicitacao()==castOther.getNsolicitacao());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNproposta();
         result = 37 * result + this.getNvendedor();
         result = 37 * result + this.getNsolicitacao();
         return result;
   }   


}


