package br.com.melhoroferta.entidades;
// Generated 10/04/2012 17:04:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private Integer nvendedor;
     private Usuario usuario;
     private Integer negativacoes;
     private Integer positivacoes;
     private Set vendedorcategoriases = new HashSet(0);
     private Set vendedorsolicitacaos = new HashSet(0);
     private Categorias categorias;

    public Vendedor(Usuario usuario) {
        this.usuario=usuario;
    }

     public Vendedor() {
    }
     
    public Vendedor(Usuario usuario, Integer negativacoes, Integer positivacoes, Set vendedorcategoriases, Set vendedorsolicitacaos, Categorias categorias) {
       this.usuario = usuario;
       this.negativacoes = negativacoes;
       this.positivacoes = positivacoes;
       this.vendedorcategoriases = vendedorcategoriases;
       this.vendedorsolicitacaos = vendedorsolicitacaos;
       this.categorias = categorias;
       
    }
    
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias (Categorias categorias) {
        this.categorias = categorias;
    }
   
    public Integer getNvendedor() {
        return this.nvendedor;
    }
    
    public void setNvendedor(Integer nvendedor) {
        this.nvendedor = nvendedor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getNegativacoes() {
        return this.negativacoes;
    }
    
    public void setNegativacoes(Integer negativacoes) {
        this.negativacoes = negativacoes;
    }
    public Integer getPositivacoes() {
        return this.positivacoes;
    }
    
    public void setPositivacoes(Integer positivacoes) {
        this.positivacoes = positivacoes;
    }
    public Set getVendedorcategoriases() {
        return this.vendedorcategoriases;
    }
    
    public void setVendedorcategoriases(Set vendedorcategoriases) {
        this.vendedorcategoriases = vendedorcategoriases;
    }
    public Set getVendedorsolicitacaos() {
        return this.vendedorsolicitacaos;
    }
    
    public void setVendedorsolicitacaos(Set vendedorsolicitacaos) {
        this.vendedorsolicitacaos = vendedorsolicitacaos;
    }

    




}


